## Homework 0 Part 2: Data Loaders

In this assignment, you will be provided with data and an expected result. Your task is to fill out the starter code to obtain the expected result. Do not modify the data (X or Y), and do not modify the instantiation of the dataset or dataloader.

All three versions -- easy difficulty, medium difficulty, and hard difficulty -- have the same solution code and the same examples. We recommend starting with the easy difficulty. Once you get the expected results with the easy difficulty, try again with the medium difficulty. If you want to challenge yourself, try again with the hard difficulty.

CUDA is not required to complete most of this assignment, but it is required to execute the final command (unless you have a GPU in your local machine). Please use AWS to access CUDA available resources by following the AWS recitation0.

Have fun!

<hr style="border:2px solid gray"> </hr>

In [2]:
import numpy as np
import torch

<hr style="border:2px solid gray"> </hr>

### Exercise 1

In [3]:
X = np.array([2,  3,  4,  5,  6,  7,  8,  9])

In [4]:
class ExampleDataset1(torch.utils.data.Dataset):
    
    def __init__(self, X):

        self.X = X
        self.length = len(X)
        
        
    def __len__(self):
        return self.length

        
    def __getitem__(self, i):
        return self.X[i]
        

        
    def collate_fn(batch):
        batch_x = torch.as_tensor(batch)
        return batch_x

        

In [5]:
dataset1 = ExampleDataset1(X)

dataloader1 = torch.utils.data.DataLoader(dataset1,
                                          batch_size=2, 
                                          shuffle=False,
                                          collate_fn=ExampleDataset1.collate_fn)

for i, batch in enumerate(dataloader1):
    print("Batch", i, ":\n", batch, "\n")

Batch 0 :
 tensor([2, 3]) 

Batch 1 :
 tensor([4, 5]) 

Batch 2 :
 tensor([6, 7]) 

Batch 3 :
 tensor([8, 9]) 



---
#### Expected Output:
```
Batch 0 :
 tensor([2, 3]) 

Batch 1 :
 tensor([4, 5]) 

Batch 2 :
 tensor([6, 7]) 

Batch 3 :
 tensor([8, 9]) 
```
---

<hr style="border:2px solid gray"> </hr>

### Exercise 2

In [6]:
X = np.array([2,  3,  4,  5,  6,  7,  8,  9])
Y = np.array([4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
class ExampleDataset2(torch.utils.data.Dataset):
    
    def __init__(self, X, Y):
        self.X = X
        self.Y = Y
        self.length = len(X)
        
        
    def __len__(self):
        return self.length
        
        
        
    def __getitem__(self, i):
        return self.X[i], self.Y[i]
        
        
    def collate_fn(batch):

        batch_x = [x for x, y in batch]
        batch_y = [y for x, y in batch]

        batch_x = torch.as_tensor(batch_x)
        batch_y = torch.as_tensor(batch_y)

        return batch_x, batch_y

        

In [8]:
dataset2 = ExampleDataset2(X, Y)

dataloader2 = torch.utils.data.DataLoader(dataset2,
                                          batch_size=2, 
                                          shuffle=False,
                                          collate_fn=ExampleDataset2.collate_fn)

for i, batch in enumerate(dataloader2):
    print("Batch", i, ":\n", batch, "\n")

Batch 0 :
 (tensor([2, 3]), tensor([4, 9])) 

Batch 1 :
 (tensor([4, 5]), tensor([16, 25])) 

Batch 2 :
 (tensor([6, 7]), tensor([36, 49])) 

Batch 3 :
 (tensor([8, 9]), tensor([64, 81])) 



---
#### Expected Output:

```
Batch 0 :
 (tensor([2, 3]), tensor([4, 9])) 

Batch 1 :
 (tensor([4, 5]), tensor([16, 25])) 

Batch 2 :
 (tensor([6, 7]), tensor([36, 49])) 

Batch 3 :
 (tensor([8, 9]), tensor([64, 81])) 

```
---

<hr style="border:2px solid gray"> </hr>

### Example 3

In [9]:
X = np.array([ np.array([[ 2,  3,  4],
                         [ 4,  6,  8],
                         [ 6,  9, 12],
                         [ 8, 12, 16]]),
               np.array([[10, 15, 20],
                         [12, 18, 24]]) ], dtype=object)

In [10]:
class ExampleDataset3(torch.utils.data.Dataset):
    
    def __init__(self, X):
        self.X = X

        index_map_X = []

        for i, x in enumerate(X):
            for j, xx, in enumerate(x):
                index_pair_X = (i, j)
                index_map_X.append(index_pair_X)
        
        self.index_map = index_map_X
        self.length = len(index_map_X)
        
        
    def __len__(self):
        return self.length
        
        
    def __getitem__(self, index):
       i, j = self.index_map[index]
       xx = self.X[i][j, :]
       return xx
        
        
    def collate_fn(batch):
        batch_x = torch.as_tensor(batch)

        return batch_x
        
        

In [11]:
dataset3 = ExampleDataset3(X)

dataloader3 = torch.utils.data.DataLoader(dataset3,
                                          batch_size=3, 
                                          shuffle=False,
                                          collate_fn=ExampleDataset3.collate_fn)

for i, batch in enumerate(dataloader3):
    print("Batch", i, ":\n", batch, "\n")

Batch 0 :
 tensor([[ 2,  3,  4],
        [ 4,  6,  8],
        [ 6,  9, 12]]) 

Batch 1 :
 tensor([[ 8, 12, 16],
        [10, 15, 20],
        [12, 18, 24]]) 



C:\Users\15144\AppData\Local\Temp\ipykernel_14452\2061146709.py:28: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_new.cpp:256.)
  batch_x = torch.as_tensor(batch)


---
#### Expected Output

```
Batch 0 :
 tensor([[ 2,  3,  4],
        [ 4,  6,  8],
        [ 6,  9, 12]]) 

Batch 1 :
 tensor([[ 8, 12, 16],
        [10, 15, 20],
        [12, 18, 24]]) 
```
---

<hr style="border:2px solid gray"> </hr>

### Exercise 4

In [12]:
X = np.array([ np.array([[ 2,  3,  4],
                         [ 4,  6,  8],
                         [ 6,  9, 12],
                         [ 8, 12, 16]]),
               np.array([[10, 15, 20],
                         [12, 18, 24]]) ], dtype=object)

Y = np.array([ np.array([1, 2, 3, 4]), 
               np.array([5, 6])], dtype=object)

In [13]:
class ExampleDataset4(torch.utils.data.Dataset):
    
    def __init__(self, X, Y):
        self.X = X
        self.Y = Y

        index_map_X = []
        index_map_Y = []

        for i, x in enumerate(X):
            for j, xx in enumerate(x):
                index_pair_x = (i, j)
                index_map_X.append(index_pair_x)
        
        for i, y in enumerate(Y):
            for j, yy in enumerate(y):
                index_pair_y = (i, y)
                index_map_Y.append(index_pair_y)
        
        self.index_map = index_map_X
        self.length = len(self.index_map)
        
        
    def __len__(self):
        return self.length
        
        
    def __getitem__(self, index):
        i, j = self.index_map[index]

        xx = self.X[i][j, :]
        yy = self.Y[i][j]
        return xx, yy
        
        
    def collate_fn(batch):
        batch_x = [x for x, y in batch]
        batch_y = [y for x, y in batch]

        batch_x = torch.as_tensor(batch_x)
        batch_y = torch.as_tensor(batch_y)

        return batch_x, batch_y
        
        

In [14]:
dataset4 = ExampleDataset4(X, Y)

dataloader4 = torch.utils.data.DataLoader(dataset4,
                                          batch_size=3, 
                                          shuffle=False,
                                          collate_fn=ExampleDataset4.collate_fn)


for i, batch in enumerate(dataloader4):
    print("Batch", i, ":\n", batch, "\n")

Batch 0 :
 (tensor([[ 2,  3,  4],
        [ 4,  6,  8],
        [ 6,  9, 12]]), tensor([1, 2, 3])) 

Batch 1 :
 (tensor([[ 8, 12, 16],
        [10, 15, 20],
        [12, 18, 24]]), tensor([4, 5, 6])) 



---
#### Expected Output:

```
Batch 0 :
 (tensor([[ 2,  3,  4],
        [ 4,  6,  8],
        [ 6,  9, 12]]), tensor([1, 2, 3])) 

Batch 1 :
 (tensor([[ 8, 12, 16],
        [10, 15, 20],
        [12, 18, 24]]), tensor([4, 5, 6]))
```
---

<hr style="border:2px solid gray"> </hr>

### Exercise 5

In [15]:
X = np.array([ np.array([[ 2,  3,  4],
                         [ 4,  6,  8],
                         [ 6,  9, 12],
                         [ 8, 12, 16]]),
               np.array([[10, 15, 20],
                         [12, 18, 24]]) ], dtype=object)

In [16]:
class ExampleDataset5(torch.utils.data.Dataset):
    
    def __init__(self, X, offset=1, context=1):
        self.X = X

        index_map_X = []
        for i, x in enumerate(X):
            for j, xx in enumerate(x):
                index_pair_x = (i, j)
                index_map_X.append(index_pair_x)
        
        self.index_map = index_map_X
        self.length = len(self.index_map)

        self.context = context
        self.offset = offset

        for i, x in enumerate(self.X):
            self.X[i] = np.pad(x, ((context, context), (0, 0)), "constant", constant_values=0)

        
    def __len__(self):
        return self.length
        
        
    def __getitem__(self, index):
        i, j = self.index_map[index]

        start_j = j + self.offset - self.context
        end_j = j + self.offset + self.context + 1

        xx = self.X[i][start_j:end_j, :]
        return xx
        
        
    def collate_fn(batch):
        batch_x = torch.as_tensor(batch)
        return batch_x
        
        

In [17]:
dataset5 = ExampleDataset5(X)

dataloader5 = torch.utils.data.DataLoader(dataset5,
                                         batch_size=2, 
                                         shuffle=False,
                                         collate_fn=ExampleDataset5.collate_fn)

for i, batch in enumerate(dataloader5):
    print("Batch", i, ":\n", batch, "\n")

Batch 0 :
 tensor([[[ 0,  0,  0],
         [ 2,  3,  4],
         [ 4,  6,  8]],

        [[ 2,  3,  4],
         [ 4,  6,  8],
         [ 6,  9, 12]]]) 

Batch 1 :
 tensor([[[ 4,  6,  8],
         [ 6,  9, 12],
         [ 8, 12, 16]],

        [[ 6,  9, 12],
         [ 8, 12, 16],
         [ 0,  0,  0]]]) 

Batch 2 :
 tensor([[[ 0,  0,  0],
         [10, 15, 20],
         [12, 18, 24]],

        [[10, 15, 20],
         [12, 18, 24],
         [ 0,  0,  0]]]) 



---
#### Expected Output:

```
Batch 0 :
 tensor([[[ 0,  0,  0],
         [ 2,  3,  4],
         [ 4,  6,  8]],

        [[ 2,  3,  4],
         [ 4,  6,  8],
         [ 6,  9, 12]]]) 

Batch 1 :
 tensor([[[ 4,  6,  8],
         [ 6,  9, 12],
         [ 8, 12, 16]],

        [[ 6,  9, 12],
         [ 8, 12, 16],
         [ 0,  0,  0]]]) 

Batch 2 :
 tensor([[[ 0,  0,  0],
         [10, 15, 20],
         [12, 18, 24]],

        [[10, 15, 20],
         [12, 18, 24],
         [ 0,  0,  0]]]) 
```
---

<hr style="border:2px solid gray"> </hr>

### Exercise 6

In [30]:
X = np.array([ np.array([[ 2,  3,  4],
                         [ 4,  6,  8],
                         [ 6,  9, 12],
                         [ 8, 12, 16]]),
               np.array([[10, 15, 20],
                         [12, 18, 24]]) ], dtype=object)

Y = np.array([ np.array([1, 2, 3, 4]), 
               np.array([5, 6])], dtype=object)

In [31]:
class ExampleDataset6(torch.utils.data.Dataset):
    
    def __init__(self, X, Y, offset=1, context=1):
        
        self.X = X
        self.Y = Y

        index_map_X = []
        for i, x in enumerate(self.X):
            for j, xx in enumerate(x):
                index_pair_x = (i, j)
                index_map_X.append(index_pair_x)

        index_map_Y = []
        for i, y, in enumerate(self.Y):
            for j, yy in enumerate(y):
                index_pair_y = (i, j)
                index_map_Y.append(index_pair_y)

        
        assert(len(index_map_X) == len(index_map_Y))

        self.index_map = index_map_X

        self.length = len(index_map_X)

        self.context = context
        self.offset = offset

        for i, x in enumerate(X):
            self.X[i] = np.pad(x, ((context, context), (0, 0)), "constant", constant_values=0)

                
        
    def __len__(self):
        return self.length

        
    def __getitem__(self, index):
        
        i, j = self.index_map[index]

        start_j = j + self.offset - self.context
        end_j = j + self.offset + self.context + 1

        xx = self.X[i][start_j:end_j]
        yy = self.Y[i][j]

        return xx, yy
        
        
    def collate_fn(batch):
        
        batch_x = [x for x, y in batch]
        batch_y = [y for x, y in batch]

        batch_x = torch.as_tensor(batch_x)
        batch_y = torch.as_tensor(batch_y)

        return batch_x, batch_y
        
        

In [32]:
dataset6 = ExampleDataset6(X, Y)

dataloader6 = torch.utils.data.DataLoader(dataset6,
                                         batch_size=2, 
                                         shuffle=False,
                                         collate_fn=ExampleDataset6.collate_fn)

for i, batch in enumerate(dataloader6):
    print("Batch", i, ":\n", batch, "\n")

Batch 0 :
 (tensor([[[ 0,  0,  0],
         [ 2,  3,  4],
         [ 4,  6,  8]],

        [[ 2,  3,  4],
         [ 4,  6,  8],
         [ 6,  9, 12]]]), tensor([1, 2])) 

Batch 1 :
 (tensor([[[ 4,  6,  8],
         [ 6,  9, 12],
         [ 8, 12, 16]],

        [[ 6,  9, 12],
         [ 8, 12, 16],
         [ 0,  0,  0]]]), tensor([3, 4])) 

Batch 2 :
 (tensor([[[ 0,  0,  0],
         [10, 15, 20],
         [12, 18, 24]],

        [[10, 15, 20],
         [12, 18, 24],
         [ 0,  0,  0]]]), tensor([5, 6])) 



---
#### Expected Output:
```
Batch 0 :
 (tensor([[[ 0,  0,  0],
         [ 2,  3,  4],
         [ 4,  6,  8]],

        [[ 2,  3,  4],
         [ 4,  6,  8],
         [ 6,  9, 12]]]), tensor([1, 2])) 

Batch 1 :
 (tensor([[[ 4,  6,  8],
         [ 6,  9, 12],
         [ 8, 12, 16]],

        [[ 6,  9, 12],
         [ 8, 12, 16],
         [ 0,  0,  0]]]), tensor([3, 4])) 

Batch 2 :
 (tensor([[[ 0,  0,  0],
         [10, 15, 20],
         [12, 18, 24]],

        [[10, 15, 20],
         [12, 18, 24],
         [ 0,  0,  0]]]), tensor([5, 6])) 
```
---

### Exercise 7

In [33]:
!nvidia-smi

Fri Jan 30 19:38:10 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.74                 Driver Version: 591.74         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti   WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   48C    P0             25W /   80W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

---
#### Expected Output (your result should look similar, but not exactly the same):
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 460.27.04    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 207...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   40C    P8     9W /  N/A |      5MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       970      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```
---